apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.albHealthCheckPath }}
spec:
  ports:
  - name: application
    port: 80
{{- if .Values.customNodePort }}
    nodePort: {{ .Values.customNodePort }}
{{- end }}
    targetPort: application
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
  type: ClusterIP
